// Catalogo unico de paneles y modulos: de aqui salen las tarjetas, las rutas (App.jsx) y las
// redirecciones de las direcciones antiguas (legacyPath). La pagina de cada path esta en routes.jsx.
// El acceso lo decide el backend (user.access); aqui solo va el codigo que pide cada modulo.
export const modulePanels = [
  {
    code: "productividad",
    title: "Panel de Productividad",
    description: "Indicadores de productividad, cumplimiento y desempeño por cartera.",
    path: "/productividad",
    accent: "primary",
    modules: [
      {
        code: "sc-tardia",
        title: "SC Tardía",
        description: "Productividad y cumplimiento de cartera tardía.",
        path: "/productividad/sc-tardia",
        legacyPath: "/sc-tardia",
        buttonLabel: "Ir a SC Tardía",
      },
      {
        code: "sc-temprana",
        title: "SC Temprana",
        description: "Productividad y cumplimiento de cartera temprana.",
        path: "/productividad/sc-temprana",
        legacyPath: "/sc-temprana",
        buttonLabel: "Ir a SC Temprana",
      },
      {
        code: "gm",
        title: "General Motors",
        description: "Seguimiento y cumplimiento de GM.",
        path: "/productividad/gm",
        legacyPath: "/gm",
        buttonLabel: "Ir a GM",
      },
      {
        code: "itau-castigo",
        title: "Itaú Castigo",
        description: "Productividad y recupero de cartera castigada Itaú.",
        path: "/productividad/itau-castigo",
        legacyPath: "/itau-castigo",
        buttonLabel: "Ir a Itaú Castigo",
      },
      {
        code: "itau-vencida",
        title: "Itaú Vencida",
        description: "Productividad y contención de cartera vencida Itaú.",
        path: "/productividad/itau-vencida",
        legacyPath: "/itau-vencida",
        buttonLabel: "Ir a Itaú Vencida",
      },
      {
        code: "itau-vigente",
        title: "Itaú Vigente",
        description: "Productividad, contención vigente y recupero castigo de los ejecutivos telefónicos Itaú.",
        path: "/productividad/itau-vigente",
        legacyPath: "/itau-vigente",
        buttonLabel: "Ir a Itaú Vigente",
      },
      {
        code: "sth",
        title: "Santander Hipotecario",
        description: "Productividad hipotecaria y productos asociados.",
        path: "/productividad/sth",
        legacyPath: "/sth",
        buttonLabel: "Ir a STH",
      },
      {
        code: "bit",
        title: "Banco Internacional Vigente",
        description: "Seguimiento y cumplimiento de BIT Cartera Vigente.",
        path: "/productividad/bit",
        legacyPath: "/bit",
        buttonLabel: "Ir a BIT Vigente",
      },
      {
        code: "bit-castigo",
        title: "Banco Internacional Castigo",
        description: "Seguimiento y cumplimiento de BIT Cartera Castigo.",
        path: "/productividad/bit-castigo",
        legacyPath: "/bit-castigo",
        buttonLabel: "Ir a BIT Castigo",
      },
      {
        code: "la-araucana",
        title: "Caja La Araucana",
        description: "Productividad La Araucana.",
        path: "/productividad/la-araucana",
        legacyPath: "/la-araucana",
        buttonLabel: "Ir a La Araucana",
      },
    ],
  },
  {
    code: "kpi",
    title: "Panel KPI",
    description: "Seguimiento diario de cumplimiento, deuda y casos asignados.",
    path: "/kpi",
    accent: "pink",
    modules: [
      {
        code: "bench",
        title: "BENCH KPI",
        description: "Comparativo diario Phoenix vs competencia con ranking y serie histórica.",
        path: "/kpi/bench",
        legacyPath: "/bench",
        buttonLabel: "Abrir BENCH KPI",
      },
      {
        code: "kpi-diario",
        title: "KPI Avance Phoenix",
        description: "Comparación mensual de Phoenix contra sí mismo por día hábil.",
        path: "/kpi/avance-phoenix",
        legacyPath: "/kpi-avance-phoenix",
        buttonLabel: "Abrir KPI Phoenix",
      },
      {
        code: "kpi-operacional",
        title: "KPI Operacional",
        description: "Asignación, saldo, contactabilidad, pagos y compromisos por mandante y cartera.",
        path: "/kpi/operacional",
        legacyPath: "/kpi-operacional",
        buttonLabel: "Abrir KPI Operacional",
      },
    ],
  },
  {
    code: "contactabilidad",
    title: "Panel de Contactabilidad",
    description: "Indicadores de contactabilidad, recurrencia, contacto titular y gestión.",
    path: "/contactabilidad",
    accent: "success",
    modules: [
      {
        code: "contactabilidad",
        title: "Itaú Vencida",
        description: "Indicadores de contactabilidad, recurrencia, contacto titular y gestión.",
        path: "/contactabilidad/itau-vencida",
        buttonLabel: "Ver detalle",
      },
    ],
  },
  {
    code: "administrativas",
    title: "Panel Administrativo",
    description: "Descargas de archivos de clientes y configuraciones internas.",
    path: "/administrativas",
    accent: "info",
    modules: [
      {
        code: "administrativas",
        title: "Itaú Vencida",
        description: "Descarga cuotas, asignación y cuotas pagadas, y define los casos medibles del mes.",
        path: "/administrativas/itau-vencida",
        legacyPath: "/administrativas/itau",
        buttonLabel: "Abrir Itaú Vencida",
      },
      {
        code: "administrativas",
        title: "Negocios",
        description: "Sube el Excel de negocios (reconducciones, refinanciamientos, novaciones, daciones, extensiones) de SC Terreno, SC Telefonía y GM.",
        path: "/administrativas/negocios",
        buttonLabel: "Abrir Negocios",
      },
      {
        // Tiene permiso propio: el panel administrativo no lo abre.
        code: "gestiones-diarias-sct",
        title: "Gestiones Diarias SCT",
        description: "Carga, resumen y detalle de gestiones diarias Santander Consumer Terreno.",
        path: "/administrativas/gestiones-diarias-sct",
        legacyPath: "/gestiones-diarias-sct",
        buttonLabel: "Ver Gestiones SCT",
      },
    ],
  },
  {
    code: "estrategia-asignacion",
    title: "Panel Estrategia de Asignación",
    description: "Reparto equilibrado de la asignación entre ejecutivos.",
    path: "/estrategia-asignacion",
    accent: "violet",
    modules: [
      {
        code: "estrategia-asignacion",
        title: "Itaú Castigo",
        description: "Reparte la asignación Phoenix del mes entre los ejecutivos, parejos en saldo, operaciones, contactabilidad, MOB y nota.",
        path: "/estrategia-asignacion/itau-castigo",
        buttonLabel: "Abrir Itaú Castigo",
      },
    ],
  },
  {
    code: "rrhh",
    title: "Panel RRHH",
    description: "Planillas de cumplimiento por negocio y consolidado del mes.",
    path: "/rrhh",
    accent: "indigo",
    modules: [
      {
        code: "rrhh",
        title: "Cumplimientos de Campañas",
        description: "Exporta las variables y el cumplimiento de cada ejecutivo por negocio, y el consolidado del mes.",
        path: "/rrhh/cumplimientos",
        buttonLabel: "Abrir Cumplimientos",
      },
    ],
  },
  {
    code: "admin",
    title: "Panel Admin",
    description: "Administración de usuarios y de sus permisos en la plataforma.",
    path: "/admin",
    accent: "danger",
    modules: [
      {
        code: "admin",
        title: "Usuarios",
        description: "Crear usuarios, asignar módulos y activar o desactivar cuentas.",
        path: "/admin/usuarios",
        buttonLabel: "Administrar Usuarios",
      },
    ],
  },
];
