export const GLOBAL_MODULE_CODE = "global";

export const modulePanels = [
  {
    code: "productividad",
    title: "Panel de Productividad",
    description: "Indicadores de productividad, cumplimiento y desempeño por cartera.",
    path: "/productividad",
    accent: "primary",
    modules: [
      {
        code: "sc-tardia",
        title: "SC Tardia",
        description: "Productividad y cumplimiento de cartera tardia.",
        path: "/sc-tardia",
        buttonLabel: "Ir a SC Tardia",
      },
      {
        code: "sc-temprana",
        title: "SC Temprana",
        description: "Productividad y cumplimiento de cartera temprana.",
        path: "/sc-temprana",
        buttonLabel: "Ir a SC Temprana",
      },
      {
        code: "gm",
        title: "General Motors",
        description: "Seguimiento y cumplimiento de GM.",
        path: "/gm",
        buttonLabel: "Ir a GM",
      },
      {
        code: "itau-castigo",
        title: "Itaú Castigo",
        description: "Productividad y recupero de cartera castigada Itaú.",
        path: "/itau-castigo",
        buttonLabel: "Ir a Itaú Castigo",
      },
      {
        code: "sth",
        title: "Santander Hipotecario",
        description: "Productividad hipotecaria y productos asociados.",
        path: "/sth",
        buttonLabel: "Ir a STH",
      },
      {
        code: "porsche",
        title: "Porsche",
        description: "Seguimiento y cumplimiento Porsche.",
        path: "/porsche",
        buttonLabel: "Ir a Porsche",
      },
      {
        code: "bit",
        title: "Banco Internacional Vigente",
        description: "Seguimiento y cumplimiento de BIT Cartera Vigente.",
        path: "/bit",
        buttonLabel: "Ir a BIT Vigente",
      },
      {
        code: "bit-castigo",
        title: "Banco Internacional Castigo",
        description: "Seguimiento y cumplimiento de BIT Cartera Castigo.",
        path: "/bit-castigo",
        buttonLabel: "Ir a BIT Castigo",
      },
      {
        code: "la-araucana",
        title: "Caja La Araucana",
        description: "Productividad La Araucana.",
        path: "/la-araucana",
        buttonLabel: "Ir a La Araucana",
      },
    ],
  },
  {
    code: "kpi",
    title: "Panel KPI",
    description: "Seguimiento diario de cumplimiento, deuda y casos asignados.",
    path: "/kpi",
    accent: "pink",
    modules: [
      {
        code: "bench",
        title: "BENCH KPI",
        description: "Comparativo diario Phoenix vs competencia con ranking y serie historica.",
        path: "/bench",
        buttonLabel: "Abrir BENCH KPI",
      },
    ],
  },
  {
    code: "contactabilidad",
    title: "Panel de Contactabilidad",
    description: "Panel reservado para futuros indicadores y procesos de contactabilidad.",
    path: "/contactabilidad",
    accent: "success",
    modules: [],
  },
  {
    code: "factura",
    title: "Panel de Factura",
    description: "Espacio preparado para facturas, reportes y procesos asociados.",
    path: "/factura",
    accent: "warning",
    modules: [],
  },
  {
    code: "administrativas",
    title: "Panel de Administrativas",
    description: "Formularios y procesos administrativos internos.",
    path: "/administrativas",
    accent: "info",
    modules: [],
  },
  {
    code: "admin",
    title: "Panel Admin",
    description: "Administracion de usuarios, permisos y configuracion de la plataforma.",
    path: "/admin",
    accent: "danger",
    adminOnly: true,
    modules: [
      {
        code: "admin",
        title: "Usuarios",
        description: "Crear usuarios, asignar modulos y activar o desactivar cuentas.",
        path: "/admin/usuarios",
        buttonLabel: "Administrar Usuarios",
      },
      {
        code: "admin",
        title: "Permisos",
        description: "Espacio reservado para administracion avanzada de permisos.",
        path: "/admin/permisos",
        buttonLabel: "Ir a Permisos",
      },
      {
        code: "admin",
        title: "Configuracion",
        description: "Espacio reservado para configuracion general de la plataforma.",
        path: "/admin/configuracion",
        buttonLabel: "Ir a Configuracion",
      },
    ],
  },
];
